version: '3'
services:
  web:
    container_name: srv-laravel
    image: lfmc/iso-laravel:0.1
    build: .
    networks:
      - red_laravel
    ports:
      - "81:80"
    volumes:
      - ./html:/var/www/html
      #- ./apache/:/usr/local/apache2/conf
      #- ./php/:/usr/local/etc/php/conf.d
  # db:
  #   container_name: srv-mysql
  #   image: mysql:5.7
  #   environment:docker
  #     MYSQL_ROOT_PASSWORD: root
  #   volumes:
  #     - ./mysql:/var/lib/mysql
  #   ports:
  #     - "3307:3306"
  #   networks:
  #     - red_laravel
networks:
  red_laravel:
